scoring:
  system: |
    You are a neutral curator for github repositories.
  fewshot: |
    Examples (format matches schema):

    Repo:
    "CLI that cross-posts your blog posts to Dev.to, Hashnode and Medium; manages canonical URLs; adds UTM; syncs updates."

    Expected JSON:
    {
      "scores": [
        { "list": "self-marketing", "score": 0.8, "why": "Publishing & cross-posting are personal promotion workflows." },
        { "list": "productivity", "score": 0.4, "why": "CLI automation helps, but promotion is the primary goal." },
        { "list": "learning", "score": 0.0 }
      ]
    }

    Repo:
    "Task-runner that automates image optimisation and builds; speeds up local dev commands; no publishing features."

    Expected JSON:
    {
      "scores": [
        { "list": "productivity", "score": 0.9, "why": "Developer time-saver for day-to-day workflows." },
        { "list": "self-marketing", "score": 0.1, "why": "Not focused on promoting an individual." },
        { "list": "learning", "score": 0.0 }
      ]
    }
  criteria:
    # This section is generated by `gk-stars setup` from your lists.
    # For each list, write a concise criterion for when to assign a non-zero score.
    # Example entry (edit as needed):
    # - slug: productivity
    #   name: Productivity
    #   description: only score if the repo saves time or automates repetitive tasks in any domain (e.g. work, study, daily life).

summarise:
  one_paragraph: |
    Write ONE paragraph (≤100 words) that explains the project in plain language 
    for a general audience with no technical background. 
    Focus on what it does and why it matters. 
    Keep it clear, simple, and factual. Do not use bullet points, headings, or em dashes.

  map_header: |
    From the following text, extract 2-3 short bullets (10-18 words each) in plain language. 
    Summarise what the project does and why it might be useful. 
    Return only bullets prefixed with "- ".

  reduce: |
    Write ONE paragraph (≤100 words) in plain language for a general audience. 
    Explain what the project does and why it might be useful. 
    Keep it clear, simple, and factual. 
    Return only the paragraph, no bullet points or em dashes.

