telemetry = false

[test]
# Coverage configuration
preload = ["./test-setup.ts"]
coverage = true
coverageDir = "./coverage"              # overridden per shard by CLI above
coverageReporter = ["text", "lcov"]     # keep text + lcov
coverageSkipTestFiles = true

# Exclude test files, fakes, and mocks from coverage
# This gives us true production code coverage metrics
coveragePathIgnorePatterns = [
  "**/*.test.ts",
  "**/*.spec.ts",
  "src/__test__/**"
]
